config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection do
      post :confirm
    end
  end
  root to: 'sessions#new'
  resources :sessions, only: [:new,:create,:destroy]
  resources :users, only: [:new,:create,:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :content,presence: true,length:{in:1..140}
  validates :title,presence: true,length:{maximum: 20}
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length:{ maximum:100}
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,presence: true,length: {maximum:30}
  validates :email,presence: true,length: {maximum:255},
                  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation {email.downcase!}
  has_secure_password
  validates :password,length: {minimum:6}
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only:[:show,:edit,:update,:destroy]

  def index
    @blogs=Blog.all
  end

  def new
    @blog =Blog.new
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "ブログを作成しました！"
      else
        render :new
      end
    end
  end

  def show
    
  end

  def edit
    if @blog.user == current_user
      render :edit
    else
      redirect_to blogs_path
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "ブログを削除しました！"
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end


  private

  def blog_params
    params.require(:blog).permit(:title, :content,:image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id]=user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger]='ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create,:show]
  def new
    @user=User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user=User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new'|| action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true,url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@blog.image.url,:size =>'640x480') if @blog.image && @blog.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <%= form.submit %>
<% end %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, local: true,url: blogs_path) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= image_tag(@blog.image.url,:size =>'640x480') if @blog.image && @blog.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/blogs/edit.html.erb
<h1>編集画面</h1>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>


<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>ユーザー</th>
    <%=content_tag(:th, notice, class: "notice")%>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= blog.user.name%></td>
    <td><%= link_to '詳細を確認する', blog_path(blog.id) %></td>
    <%if blog.user.id == current_user.id%>
      <td><%= link_to 'ブログを編集する', edit_blog_path(blog.id) %></td>
      <td><%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete ,data: {confirm: '本当に削除しますか？'}%></td>
    <%end%>
  </tr>
<% end %>
</table>


<style>
h1{
  padding:20px;
  font-size: 20px;
}
td{
  padding: 20px;
  border:solid 2px #808080;
}
tr{
  padding: 20px;
  border:solid 2px #808080;
}
.notice{
  color: #ff0000;
}
</style>

app/views/blogs/new.html.erb
<h1>新規投稿</h1>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<h2>タイトル: <%= @blog.title %></h2>
<p>内容: <%= @blog.content %></p>
<p>画像: <br><%= image_tag(@blog.image.url,:size =>'640x480') if @blog.image && @blog.image.url %><p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HawkApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      body{min-height: 100vh; display: flex;}
      .right{text-align: center; border-right: solid 3px #808080}
      .left{text-align: center;}
      .bi-patch-check{font-size:50px;}
      .bi-layout-text-sidebar{font-size:50px;}
      .bi-file-person{font-size:50px;}
    </style>
  </head>

  <body>
    <div class="left">
    </div>
    <div class="right">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <% if logged_in? %>
        <p>現在ログインしているのは：<%=current_user.name%></p>
        <%=link_to(new_blog_path)do%>
          <i class="bi bi-patch-check"></i>
        <%end%>
        <br>
        <%=link_to(blogs_path)do%>
          <i class="bi bi-layout-text-sidebar"></i>
        <%end%>
        <br>
        <%=link_to(user_path(current_user.id))do %>
          <i class="bi bi-file-person"></i>
        <%end%>
        <br>
        <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_path %><br>
        <%= link_to "Login", new_session_path %>
      <% end %>
    </div>

    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/new.html.erb
<h1>サインイン</h1>
<%if @user.errors.any?%>
  <div id="error_explanation">
    <h2><%=pluralize(@user.errors.count,"error")%>prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
      <%@user.errors.full_messages.each do |message|%>
        <li><%= message %></li>
      <%end%>
    </ul>
  </div>
<%end%>

<%=form_with(model: @user,local: true) do |f|%>
  <%=f.label :name%>
  <%=f.text_field(:name) %>

  <%=f.label :email%>
  <%=f.email_field(:email) %>

  <%=f.label :password%>
  <%=f.password_field(:password) %>

  <%=f.label :password_confirmation%>
  <%=f.password_field(:password_confirmation) %>

  <%=f.submit "登録"%>

<%end%>

app/views/users/show.html.erb
<p><%= @user.name %>のページ</p>

<p>メールアドレス: <%= @user.email %></p>